-- Run this in Supabase SQL Editor to allow authenticated users to read/write forum_posts.
-- This fixes: new row violates row-level security policy for table "forum_posts"

-- Standard forum post schema: id is the primary key, author_id links to auth.users.
do $$
begin
	if not exists (
		select 1
		from information_schema.columns
		where table_schema = 'public'
		  and table_name = 'forum_posts'
		  and column_name = 'author_id'
	) then
		alter table public.forum_posts add column author_id uuid;
	end if;

	alter table public.forum_posts alter column author_id set default auth.uid();

	if not exists (
		select 1
		from information_schema.columns
		where table_schema = 'public'
		  and table_name = 'forum_posts'
		  and column_name = 'created_at'
	) then
		alter table public.forum_posts add column created_at timestamptz not null default now();
	end if;

	if not exists (
		select 1
		from information_schema.columns
		where table_schema = 'public'
		  and table_name = 'forum_posts'
		  and column_name = 'author_name'
	) then
		alter table public.forum_posts add column author_name text;
	end if;

	alter table public.forum_posts alter column author_name set default '會員';

	if not exists (
		select 1
		from information_schema.columns
		where table_schema = 'public'
		  and table_name = 'forum_posts'
		  and column_name = 'id'
	) then
		alter table public.forum_posts add column id bigint;
	end if;

	with numbered as (
		select ctid, row_number() over (order by ctid) as rn
		from public.forum_posts
		where id is null
	)
	update public.forum_posts f
	set id = numbered.rn + coalesce((select max(id) from public.forum_posts where id is not null), 0)
	from numbered
	where f.ctid = numbered.ctid;

	if not exists (
		select 1
		from pg_class
		where relkind = 'S'
		  and relnamespace = 'public'::regnamespace
		  and relname = 'forum_posts_id_seq'
	) then
		create sequence public.forum_posts_id_seq;
	end if;

	perform setval('public.forum_posts_id_seq', coalesce((select max(id) from public.forum_posts), 0) + 1, false);
	alter sequence public.forum_posts_id_seq owned by public.forum_posts.id;
	alter table public.forum_posts alter column id set default nextval('public.forum_posts_id_seq'::regclass);
	alter table public.forum_posts alter column id set not null;

	if not exists (
		select 1
		from pg_constraint
		where conname = 'forum_posts_author_id_fkey'
		  and conrelid = 'public.forum_posts'::regclass
	) then
		alter table public.forum_posts
			add constraint forum_posts_author_id_fkey
			foreign key (author_id)
			references auth.users(id)
			on delete cascade;
	end if;

	if exists (
		select 1
		from pg_constraint c
		where c.conrelid = 'public.forum_posts'::regclass
		  and c.contype = 'p'
		  and exists (
			select 1
			from unnest(c.conkey) as key_attnum(attnum)
			join pg_attribute a
			  on a.attrelid = c.conrelid
			 and a.attnum = key_attnum.attnum
			where a.attname = 'bug_id'
		  )
		  and not exists (
			select 1
			from unnest(c.conkey) as key_attnum(attnum)
			join pg_attribute a
			  on a.attrelid = c.conrelid
			 and a.attnum = key_attnum.attnum
			where a.attname = 'id'
		  )
	) then
		alter table public.forum_posts drop constraint forum_posts_pkey;
		alter table public.forum_posts add constraint forum_posts_pkey primary key (id);
	end if;
end $$;

create table if not exists public.forum_post_votes (
	id bigint generated by default as identity primary key,
	post_id bigint not null references public.forum_posts(id) on delete cascade,
	voter_id uuid not null references auth.users(id) on delete cascade,
	created_at timestamptz not null default now(),
	constraint forum_post_votes_unique unique (post_id, voter_id)
);

create or replace function public.bump_forum_post_vote_count()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
	if tg_op = 'INSERT' then
		update public.forum_posts
		set votes = coalesce(votes, 0) + 1
		where id = new.post_id;
		return new;
	elsif tg_op = 'DELETE' then
		update public.forum_posts
		set votes = greatest(coalesce(votes, 0) - 1, 0)
		where id = old.post_id;
		return old;
	end if;

	return null;
end;
$$;

drop trigger if exists forum_post_votes_insert_trigger on public.forum_post_votes;
create trigger forum_post_votes_insert_trigger
after insert on public.forum_post_votes
for each row execute function public.bump_forum_post_vote_count();

drop trigger if exists forum_post_votes_delete_trigger on public.forum_post_votes;
create trigger forum_post_votes_delete_trigger
after delete on public.forum_post_votes
for each row execute function public.bump_forum_post_vote_count();

alter table public.forum_posts enable row level security;

-- Read access for all authenticated users
drop policy if exists "forum_posts_select_authenticated" on public.forum_posts;
create policy "forum_posts_select_authenticated"
on public.forum_posts
for select
to public
using (true);

-- Insert access for authenticated users
drop policy if exists "forum_posts_insert_authenticated" on public.forum_posts;
create policy "forum_posts_insert_authenticated"
on public.forum_posts
for insert
to authenticated
with check (author_id = auth.uid());

-- Update access for authenticated users
drop policy if exists "forum_posts_update_authenticated" on public.forum_posts;
create policy "forum_posts_update_authenticated"
on public.forum_posts
for update
to authenticated
using (true)
with check (true);

-- Optional: delete access for authenticated users
drop policy if exists "forum_posts_delete_authenticated" on public.forum_posts;
create policy "forum_posts_delete_authenticated"
on public.forum_posts
for delete
to authenticated
using (author_id = auth.uid());

alter table public.forum_post_votes enable row level security;

drop policy if exists "forum_post_votes_select_own" on public.forum_post_votes;
create policy "forum_post_votes_select_own"
on public.forum_post_votes
for select
to authenticated
using (voter_id = auth.uid());

drop policy if exists "forum_post_votes_insert_own" on public.forum_post_votes;
create policy "forum_post_votes_insert_own"
on public.forum_post_votes
for insert
to authenticated
with check (voter_id = auth.uid());

drop policy if exists "forum_post_votes_delete_own" on public.forum_post_votes;
create policy "forum_post_votes_delete_own"
on public.forum_post_votes
for delete
to authenticated
using (voter_id = auth.uid());
